name: Weather Push

on:
  schedule:
    - cron: '30 22 * * *'  # 北京时间早上6:30触发（UTC时间22:30）
  workflow_dispatch:  # 允许手动触发

jobs:
  weather-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get and push weather info
        env:
          CAIYUN_API_KEY: ${{ secrets.CAIYUN_API_KEY }}
          PUSHDEER_KEY: ${{ secrets.PUSHDEER_KEY }}
        run: |
          python - <<EOF
          import requests
          import json
          import os
          from datetime import datetime, timedelta

          # 彩云天气API
          location = "121.4737,31.2304"  # 上海徐汇区经纬度
          api_url = f"https://api.caiyunapp.com/locationByCityName/Shanghai/{os.getenv('CAIYUN_API_KEY')}.json"

          # 获取天气数据
          response = requests.get(api_url)
          weather_data = response.json()

          # 解析天气数据
          day_weather = weather_data['result']['realtime']['skycon']
          min_temp = weather_data['result']['daily']['temperature'][0]['min']
          max_temp = weather_data['result']['daily']['temperature'][0]['max']
          precipitation = weather_data['result']['daily']['precipitation'][0]['status']

          # 组装天气信息
          weather_info = f"今天的天气：白天 {day_weather}，最低温度 {min_temp} 度，最高温度 {max_temp} 度。降水情况：{precipitation}\n"

          # 获取未来一周天气数据
          for i in range(1, 8):
              date = (datetime.now() + timedelta(days=i)).strftime("%Y-%m-%d")
              day_temp = weather_data['result']['daily']['temperature'][i]['max']
              night_temp = weather_data['result']['daily']['temperature'][i]['min']
              precip = weather_data['result']['daily']['precipitation'][i]['status']
              weather_info += f"{date}：白天最高温度 {day_temp} 度，夜间最低温度 {night_temp} 度，降水情况：{precip}\n"

          # 推送天气信息到PushDeer
          push_url = f"https://api2.pushdeer.com/message/push?pushkey={os.getenv('PUSHDEER_KEY')}&text={weather_info}"
          requests.get(push_url)
          EOF
