name: Weather Push

on:
  schedule:
    - cron: '30 22 * * *'  # UTC时间22:30（北京时间6:30）
  workflow_dispatch:

jobs:
  weather-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run weather push
        env:
          CAIYUN_API_KEY: ${{ secrets.CAIYUN_API_KEY }}
          PUSHDEER_KEY: ${{ secrets.PUSHDEER_KEY }}
          WEATHER_LOCATIONS: ${{ secrets.WEATHER_LOCATIONS }}
        run: |
          python weather_push.py
